Final part
globant-ui-rosario/ChuckConde_rosario-web-ui-bootcamp-10-2017 pull request #5
Opened 2017-11-02 14:07 UTC by ChuckConde

Exercise 5 with the files now on ecma5 on the folder dist

2017-11-06 11:50 UTC, pabloascencao requested changes
Fijate que subiste los archivos compilados. esos no tendrian que estar. Solo los archivos fuente y la configuración

2017-11-06 11:50 UTC, pabloascencao commented on Topic 02/src/eventEmitter.js
> +        if (this.events[eventName]) {
en este caso se puede hacer lo siguiente: 
```
this.events[eventName] = this.events[eventName] || [];
this.events[eventName].push(callback)
```

y tendria que andar de la misma manera

2017-11-06 11:50 UTC, pabloascencao commented on Topic 02/src/movie.js
> +            for (let i = 0; i < cast.length; i++) {
no podrias usar el `.map()` en este caso?

2017-11-14 13:11 UTC, pabloascencao requested changes

2017-11-14 13:11 UTC, pabloascencao commented on Topic 02/src/eventEmitter.js
> +        if (this.events[eventName] = this.events[eventName] || []) {
fijate que en otro PR te hice un comentario sobre esto

2017-11-14 13:11 UTC, pabloascencao commented on Topic 02/src/movie.js
> +        this.title = title;
seria bueno que estas props las definas antes del constructor y que le pongas el tipo correspondiente

2017-11-14 15:23 UTC, ChuckConde commented on Topic 02/src/movie.js
> +        this.title = title;
Pero puedo poner el type aca? El archivo es js no ts y el visual ya me tira que no se puede

2017-11-14 16:26 UTC, pabloascencao commented on Topic 02/src/movie.js
> +        this.title = title;
mmm me sebe con lo que venia viendo, dejalo a esto

2017-11-14 19:24 UTC, merged