Topic 3 exercise 2
globant-ui-rosario/ChuckConde_rosario-web-ui-bootcamp-10-2017 pull request #7
Opened 2017-11-06 05:04 UTC by ChuckConde

Second Exercise

2017-11-06 12:31 UTC, pabloascencao requested changes

2017-11-06 12:31 UTC, pabloascencao commented on Topic03/Practice/src/app/app.component.ts
> +  title = 'app';
defini que tipo de variable es `title`

2017-11-06 12:31 UTC, pabloascencao commented on Topic03/Practice/src/app/home/home.component.scss
> +    width: 20rem;
medidas en `px`.

2017-11-14 11:27 UTC, ChuckConde commented
I already made the fixes to the code

2017-11-14 12:59 UTC, pabloascencao requested changes

2017-11-14 12:59 UTC, pabloascencao commented on Topic03/Practice/src/app/details/details.component.ts
> +      const id = params['id'];
No podes usar el dot notation acá?

2017-11-14 12:59 UTC, pabloascencao commented on Topic03/Practice/src/app/home/home.component.html
> +<div class="card" *ngFor="let movie of movies, let i = index">
para que estas usando en indice?

2017-11-14 12:59 UTC, pabloascencao commented on Topic03/Practice/src/app/movies.service.ts
> +    return this.http
ayer no estuviste cuando lo dije, pero en este caso vos tenes la llamada y el `.map` que haces que se repite en todas las requests. Lo que podrias hacer es un servicio que se ocupe de las cosas que repetis en todas las llamadas y que lo unico que necesites pasarle sea la URL y el metodo y que lo demas ya te venga cocinado.

2017-11-14 12:59 UTC, pabloascencao commented on Topic03/Practice/src/app/nav-bar/nav-bar.component.html
> +  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
Me suena que esto es bootstrap, por las dudas no estas usando el bootstrap para angular 2 que viene directamente con los componentes no?

2017-11-14 15:26 UTC, ChuckConde commented on Topic03/Practice/src/app/details/details.component.ts
> +      const id = params['id'];
Si, totalmente, ahi lo cambie

2017-11-14 15:26 UTC, ChuckConde commented on Topic03/Practice/src/app/home/home.component.html
> +<div class="card" *ngFor="let movie of movies, let i = index">
Absolutamente para nada, se me escapo

2017-11-14 15:27 UTC, ChuckConde commented on Topic03/Practice/src/app/movies.service.ts
> +    return this.http
Sisi, lo que dijiste hoy, se entiende

2017-11-14 15:28 UTC, ChuckConde commented on Topic03/Practice/src/app/nav-bar/nav-bar.component.html
> +  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
Si, igual era para probarlo, se que no andarian varias partes, en el projecto final las cosas de bootstrap que no funcionaban las termine sacando

2017-11-17 19:14 UTC, pabloascencao approved these changes

2017-11-17 19:35 UTC, merged