Topic 3 exercise 3
globant-ui-rosario/ChuckConde_rosario-web-ui-bootcamp-10-2017 pull request #8
Opened 2017-11-06 06:31 UTC by ChuckConde

Final Part

2017-11-06 20:16 UTC, pabloascencao requested changes

2017-11-06 20:16 UTC, pabloascencao commented on Topic03/Practice/src/app/details/details.component.ts
> +  editSummary = false;
en el detalle de una movie `Movie` no podria ser opcional. Si fuera una pagina para crear una nueva o editar entonces la variable `editSummary` podria ser True en el caso que Movie no exista o no este definida

2017-11-06 20:16 UTC, pabloascencao commented on Topic03/Practice/src/app/home/home.component.ts
> +    const newMovie = {
aca podes hacer `const newMovie =  new Movie({....})`

2017-11-06 20:16 UTC, pabloascencao commented on Topic03/Practice/src/app/movie.ts
> +    stars: Object[];
acordate de lo que hablamos en la standup

2017-11-06 20:16 UTC, pabloascencao commented on Topic03/Practice/src/app/movies.service.ts
> +      .get('/assets/movies.json')
Fijate, no podes settear en los headers de la request que la info que estas pidiendo sea `json` en vez de tener que parsearla despues?

2017-11-14 11:32 UTC, ChuckConde commented on Topic03/Practice/src/app/details/details.component.ts
> +  editSummary = false;
Dale ahi lo cambio

2017-11-14 11:32 UTC, ChuckConde commented on Topic03/Practice/src/app/home/home.component.ts
> +    const newMovie = {
Si, no me habia dado cuenta

2017-11-14 11:32 UTC, ChuckConde commented on Topic03/Practice/src/app/movie.ts
> +    stars: Object[];
Ahora trato de hacer memoria bien

2017-11-14 11:33 UTC, ChuckConde commented on Topic03/Practice/src/app/movies.service.ts
> +      .get('/assets/movies.json')
Ahora reviso bien como hacerlo

2017-11-17 17:09 UTC, ChuckConde commented on Topic03/Practice/src/app/movies.service.ts
> +      .get('/assets/movies.json')
Esto hay que usarlo por lo que lei

2017-11-17 19:06 UTC, pabloascencao approved these changes

2017-11-17 19:37 UTC, merged